name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "GP-Registrations-Management-Information-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

stages:
  - template: ./templates/deploy-env-proxy.yml
    parameters:
      apim_env: internal-dev
      target_env: dev
      depends_on: []
      base_path: gp-registrations-mi
      post_deploy:
        - template: ./templates/run-smoke-tests.yml
          parameters:
            api_name: gp-registrations-management-information
            apim_env: internal-dev
            base_path: gp-registrations-mi

  - template: ./templates/deploy-env-proxy.yml
    parameters:
      apim_env: internal-dev-sandbox
      target_env: sandbox
      depends_on: []
      base_path: gp-registrations-mi
      post_deploy:
        - template: ./templates/run-smoke-tests.yml
          parameters:
            api_name: gp-registrations-management-information
            apim_env: internal-dev-sandbox
            base_path: gp-registrations-mi

  # - template: ./templates/deploy-env-proxy.yml
  #   parameters:
  #     apim_env: int
  #     target_env: dev
  #     depends_on:
  #       - internal_dev
  #       - internal_dev_sandbox
  #     base_path: gp-registrations-mi
  #     post_deploy: []

  # - template: ./templates/deploy-env-proxy.yml
  #   parameters:
  #     apim_env: sandbox
  #     target_env: sandbox
  #     depends_on:
  #       - internal_dev
  #       - internal_dev_sandbox
  #     base_path: gp-registrations-mi
  #     post_deploy: []

  # - template: azure/common/deploy-manual-approval.yml
  #   parameters:
  #     stage_name: manual_approval
  #     depends_on:
  #       - int
  #       - sandbox
  #     manual_approval_env: manual-approval-prod

  # - template: ./templates/deploy-env-proxy.yml
  #   parameters:
  #     apim_env: prod
  #     target_env: prod
  #     depends_on:
  #       - manual_approval
  #     base_path: gp-registrations-mi
  #     post_deploy: []
