name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build And Create Artifact
        timeoutInMinutes: 40

        pool:
          name: 'AWS-ECS'

        workspace:
          clean: all

        steps:
          - checkout: self
            persistCredentials: true

          - bash: |
              echo hello
            displayName: Docker build
