openapi: "3.0.0"
x-nhs-api-spec-guid: 4631c387-3793-4413-8c61-395e014864b2
x-meta:
  service_name: "gp-registrations-management-information"
  short_service_name: "gprmi"
  product_display_name: "GP Registrations Management Information API"
  service_base_path: "gp-registrations-mi"
  product_description: "An API to capture GP Registrations management information (MI)"
  pipeline_name_prefix: "GP-Registrations-Management-Information"
info:
  version: 0.0.1
  title: GP Registrations Management Information API
  description: |
    # Overview
    Use this API to send real-time management information about GP registrations to us at NHS Digital.
    
    Currently you can send us information about the following type of events:
    - when GP2GP registrations started
    - when an EHR has been Generated
    
    This API replaces the existing weekly submission of GP2GP information sent to us via a MESH mailbox, as required by GP2GP V2.2b.
  license:
    name: MIT
  contact:
    url: 'https://nhsconnect.github.io/prm-external-developer-website/rfcs/'
    email: ian.griffiths12@nhs.net
paths:
  /registration/{version}/{registrationEvent}:
    post:
      summary: Submit registration event
      operationId: postData
      description: |
        Use this endpoint to submit GP registration management information.
        See the [the GP registration management information RFC](https://nhsconnect.github.io/prm-external-developer-website/rfcs/) for how to structure the payload data.
      parameters:
        - name: version
          in: path
          required: true
          description: The API version, currently v1
          schema:
            type: string
        - name: registrationEvent
          in: path
          required: true
          description: The type of registration event to be recorded
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            'application/json': {}
