parameters:
  - name: api_name
    default: gp-registrations-management-information
  - name: apim_env
    values:
      - internal-dev
      - internal-dev-sandbox
      - internal-qa
      - internal-qa-sandbox
      - ref
      - dev
      - int
      - sandbox
      - prod
      - manual-approval

  - name: base_path

  - name: post_deploy
    type: stepList
    default: []

  - name: depends_on
    type: object

  - name: target_env
    values:
      - dev
      - sandbox
      - prod

  - name: is_pr
    type: boolean
    default: false

stages:
  - stage: ${{ replace(parameters.apim_env, '-', '_') }}
    dependsOn: ${{ parameters.depends_on }}
    jobs:
      - deployment: deploy
        environment: ${{ parameters.apim_env }}
        pool:
          name: 'AWS-ECS'
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./get-build-artifact.yml
                - template: ./setup-proxygen-cli.yml
                - bash: |
                    set -e
                    cd specification/x-nhsd-apim
                    mv -f target-${{ parameters.target_env }}.yaml target.yaml
                    mv -f access-${{ parameters.apim_env }}.yaml access.yaml
                  displayName: Set environment specific config in x-nhsd-apim

                - ${{ if parameters.is_pr }}:
                    - bash: |
                        set -e
                        echo "##vso[task.setvariable variable=BASE_PATH_SUFFIX]-${{ replace(replace(replace(variables['Build.SourceBranch'], '/merge', ''), 'refs/pull/', ''), '/', '_') }}"
                      displayName: Set instance name suffix

                - bash: |
                    set -e
                    poetry run proxygen instance deploy --no-confirm ${{ parameters.apim_env }} ${{ parameters.base_path }}$(BASE_PATH_SUFFIX) specification/${{ parameters.api_name }}.yaml
                  displayName: Deploy proxy

                - ${{ each post_deploy_step in parameters.post_deploy }}:
                    - ${{ post_deploy_step }}

