access:
  - title: GP Registrations Management Information API (Internal Development Environment)
    grants:
      app-level0: []
    visible: true
target:
  type: external
  url: https://01ycrxiip2.execute-api.eu-west-2.amazonaws.com/dev-env
  healthcheck: /_status
  security:
    type: apikey
    header: X-API-Key
    secret: apikey
