access:
  - title: GP Registrations Management Information API (Production Environment)
    grants:
      app-level0: []
    visible: true
target:
  type: external
  url: https://u0r7aqgvvj.execute-api.eu-west-2.amazonaws.com/prod-env
  healthcheck: /_status
  security:
    type: apikey
    header: X-API-Key
    secret: apikey
